name = "CyclotomicFunctionFields"
version = "0.1.0"
defaultTargets = ["CyclotomicFunctionFields"]

[[lean_lib]]
name = "CyclotomicFunctionFields"

[[require]]
name = "mathlib"
scope = "leanprover-community"
